work_dir: /data/home/mk/AimCLR/work_dir/ntu60_cv/aimclr_bone/linear_eval/label_percent_0.01

# weights: /data/gty/released_model/ntu60_xview_bone.pt
weights:  /data/home/mk/AimCLR/work_dir/ntu60_cv/aimclr_bone/pretext/dim_256/xview_bone/epoch300_model.pt
ignore_weights: [encoder_q.fc, encoder_k, queue, mu, kappa, alpha, encoder_q.slot_attn, to_q, to_v, to_k, slot_attn, decoder_r, encoder_q.dense, decoder_m]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_semi
train_feeder_args:
  data_path: /data/home/mk/RMCL/datasets/ntu60_frame50/xview/train_position.npy
  label_path: /data/home/mk/RMCL/datasets/ntu60_frame50/xview/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /data/home/mk/RMCL/datasets/ntu60_frame50/xview/val_position.npy
  label_path: /data/home/mk/RMCL/datasets/ntu60_frame50/xview/val_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 512
  num_class: 60
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 24.
optimizer: SGD
step: [80]

# training
device: [1]
batch_size: 256
test_batch_size: 256
num_epoch: 100
stream: 'bone'

# log
save_interval: -1
eval_interval: 5
